const fs = require('fs');
let code = fs.readFileSync('src/types.ts', 'utf8');
const target = `  status: WorkflowStatus;
  verification: VerificationStatus;`;
const replacement = `  status: WorkflowStatus;
  verification: VerificationStatus;
  startedAt?: number;
  solvedAt?: number;`;
code = code.replace(target, replacement);
fs.writeFileSync('src/types.ts', code);
